# Travis Build Multiple Docker Images from a Single Repo
# https://stackoverflow.com/questions/39422135/travis-build-multiple-docker-images-from-a-single-repo

sudo: required

matrix:
      
services:
  - docker

env:

before_install:

install:

before_script: 

script:
  - echo ' -----------------  BUILD IMAGES ----------------- ' && bash build.sh

before_deploy:

deploy:
  provider: script
  script: echo "REGISTRY_PASS $REGISTRY_PASS" && echo "REGISTRY_USER $REGISTRY_USER" && export REGISTRY_PASS=$REGISTRY_PASS && export REGISTRY_USER=$REGISTRY_USER && bash deploy_dockerhub.sh 
  on:
    branch: master
after_deploy: